/*
 * Please do not edit this file -- it ensures that your package will export a
 * C routine, 'run_testthat_tests()', that can be used to run the Catch unit
 * tests available in your package.
 */
#define TESTTHAT_TEST_RUNNER
#include <testthat.h>
